version: '3'

services:
  # mariadb:
  #   image: mariadb:10.11
  #   environment:
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: myuser
  #     MYSQL_PASSWORD: mypassword
  #     MYSQL_ROOT_PASSWORD: myrootpassword
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

  # phpmyadmin:
  #   image: phpmyadmin:5.2
  #   environment:
  #     PMA_HOST: mariadb
  #     MYSQL_ROOT_PASSWORD: myrootpassword
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - mariadb
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./data2:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: myadminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
